console.log('[TEST2] Starting...');
import { adminPassword, adminUser, buildMode, buildTimeoutMs, contentReviewFailClosed, contentReviewExternalEndpoint, contentReviewExternalToken, contentReviewMaxTextBytes, contentReviewMode, dataDir, demoDbAdminHost, demoDbAdminPassword, demoDbAdminPort, demoDbAdminUser, demoDbEnabled, demoDbHost, demoDbMock, demoDbPort, demoRoot, deployRateLimit, deployRateWindowMs, dockerCpus, dockerImage, dockerMemory, emailVerificationEnabled, maxExtractedBytes, maxExtractedFiles, maxZipSizeMb, plans, port, redisHost, redisPort, publicBaseUrl, runtimeCpus, runtimeDriver, runtimeDockerImage, runtimeEnabled, runtimeRootDir, runtimeMaxInstances, runtimeMemory, runtimeNodeEnabled, runtimeStartTimeoutSeconds, runtimeTtlMinutes, serviceVersion, smtpFrom, smtpHost, smtpPass, smtpPort, smtpSecure, smtpUser, uploadDir, usageFlushIntervalMs } from './config.js';
import logger from './lib/logger.js';
import { putFile, putDirectory, deletePrefix, isMinioBackend } from './lib/storage.js';
import { purgeCache, getCacheHeaders, getCdnInfo } from './lib/cdn.js';
import { isMysqlConfigured, readDataFile, writeDataFile } from './db/mysql-store.js';
import { closePool } from './db/mysql.js';
import { userDeployEvents } from './services/deploy-event-service.js';
import { filterFeedback, normalizeFeedbackStatus, normalizeFeedbackType, publicFeedback } from './services/feedback-service.js';
import { classifyFailureCategory, createFailureDiagnosis } from './services/failure-diagnosis-service.js';
import { createExternalBackendConfigStatus, createExternalBackendConfigWithConnection, externalBackendEnvKeys, externalBackendEnvValues, hasSupabaseProject, isUnsafeExternalSecretKey, publicExternalBackend } from './services/external-backend-service.js';
import { createApplicationReadiness, publicApplicationReadiness } from './services/application-readiness-service.js';
import { calculateFormQuota, defaultFormFields, filterAdminForms, normalizeFormFields, normalizeFormStatus, publicForm, publicFormSubmission, sanitizeSubmissionPayload } from './services/form-service.js';
import { filterPlanRequests, normalizePlanRequestStatus, normalizeRequestedPlan, publicPlanRequest } from './services/plan-request-service.js';
import { calculateQuota as calculateUserQuota, getDeployEvents } from './services/quota-service.js';
import { adminUserSummary, filterAdminUsers, publicUser } from './services/user-service.js';
import { publicUserDemo, createRuntimeConfigStatus, publicRuntimeEnv, runtimeEnvForDemo, mergeRuntimeEnv } from './lib/admin-helpers.js';
import { createHostingCapabilities, createProjectArchitecture } from './services/hosting-architecture-service.js';
import { classifyProject } from './services/project-classifier-service.js';
import { createDemoDatabase, deleteDemoDatabase, demoDatabaseBlockReason, demoDatabaseEnv, initializeDemoDatabase, isDemoDatabaseReady, needsMysqlDatabase, publicDemoDatabase, resetDemoDatabase } from './services/demo-database-service.js';
import { canStartNodeRuntime, createRuntimeConfig, detectInspectionType, detectRuntimeMetadata, detectRuntimeWarnings, findRuntime, formatRuntimeFramework, inferNodeFramework, inferRuntimeEngine, isSingleServiceSsrProfile, listRuntimeRecords, prepareRuntimeProject, proxyRuntimeRequest, shouldBuildBeforeNodeStart, startNodeRuntime, stopExpiredRuntimes, stopRuntime } from './services/runtime-service.js';
import { hashPassword, verifyPassword, hashVerificationCode, createVerifyEmailCode } from './lib/password-utils.js';
import { normalizeEmail, createLoginRateLimiter } from './lib/login-rate-limiter.js';
import { createSessionStore, setSessionCookie, createAgentTokenRecord, publicAgentToken, verifyAgentToken, parseAgentToken } from './lib/session-store.js';
import { createDeployRateLimiter } from './lib/deploy-rate-limiter.js';
import { requestIdMiddleware } from './middleware/request-id.js';
import { securityHeadersMiddleware } from './middleware/security.js';
import { createRateLimiter, createStrictRateLimiter } from './middleware/rate-limiter.js';
import { isEmailConfigured, sendVerificationEmail, createSmtpMailer, sendExpirationReminderEmail } from './email/mailer.js';
import { checkAndRemindExpiringDemos } from './services/demo-expiration-service.js';
import { createAuthMiddleware } from './middleware/auth.js';
console.log('[TEST2] All custom module imports loaded');
const app = express();
app.listen(3001, () => console.log('[TEST2] LISTENING 3001'));
